//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubHorizon.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingInfo
    {
        public int OrderId { get; set; }
        public string Userid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string Phone { get; set; }
        public Nullable<int> TotalSlot { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string TransectionStatus { get; set; }
        public string TransectionNumber { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public Nullable<bool> IsRefunded { get; set; }
        public Nullable<System.DateTime> RefundedOn { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
    }
}
