//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubHorizon.Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSlotMaster
    {
        public int TimeSlotId { get; set; }
        public Nullable<int> LocId { get; set; }
        public string TimeSlot { get; set; }
        public string Days { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
